name: ratchagitja scraper

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: ./scraper/package-lock.json
      - run: npm install
        working-directory: ./scraper
      - run: npm run scrape
        working-directory: ./scraper
        env:
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
      - name: commit file
        run: |
          git config --local user.email "ratchagitja@users.noreply.github.com"
          git config --local user.name "ratchagitja"
          git add ./data/ratchakitcha.csv
          if ! git diff-index --quiet HEAD ./data/ratchakitcha.csv; then
            git commit -m "docs: auto update ratchakitcha.csv"
            git push
          fi
  extract:
    needs: scrape # wait scrape finished
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: ./extractor/package-lock.json
      - run: npm install
        working-directory: ./extractor
      - run: npm run extract
        working-directory: ./extractor
      - name: commit files
        run: |
          git config --local user.email "ratchagitja@users.noreply.github.com"
          git config --local user.name "ratchagitja"
          git add ./entries/**/*.md
          if ! git diff-index --quiet HEAD ./entries/**/*.md; then
            git commit -m "docs: auto entries"
            git push
          fi
